### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ampferl** [Social-Fire-HQ/website#1]
- [x] Change absolute URLs to relative URLs
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Anmeldeseite.html#L11
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Anmeldeseite.html#L48
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Einsatzbericht.html#L11
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Home.html#L82
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L11
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L34
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L37
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L40
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L43
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L46
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L49
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L52
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L55
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L68
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L82
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L92
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L101
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/PlannerQuickview.html#L112
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Profil.html#L12
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Profil.html#L24
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Profil.html#L112
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/QuizztemplateEineL%C3%B6sung.html#L12
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Register.html#L12
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/plannerSettings.html#L12
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/plannerSettings.html#L24
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/plannerSettings.html#L25

- [x] Remove Line
https://github.com/Social-Fire-HQ/website/blob/00e5ab51cc889228d923dc0628b020747f150769/Einsatzbericht.html#L12

- [x] Move the darkmode.css to assets/css

**Comment by MengiFFW** [comment]
Hi,

you mean make a new directory in the Repository for Assets and a subfolder for CSS or a subfolder within the webpage folder?

**Comment by Ampferl** [comment]
yes, create a new folder named assets and in it, another subdirectory named css.
Like this:
```
website/
│   ├─ assets/
│   │   ├─ css/
│   │   │   ├─ Darkmode.css
│   │   ├─ images/
│   │   │   ├─ example.jpeg
│   │   ├─ js/
│   │   │   ├─ example.js
├─ index.html
├─ Profil.html
├─ ....
```

**Comment by MengiFFW** [comment]
Did this. Now the Homepage dosen't load the css file. Do i have to change the reverence inside the html sides to assets/css/Darkmode.css?

**Comment by MengiFFW** [comment]
Tested, works, will change it this afternoon.
