### ISSUE TITLE
JS or Backend

### ISSUE THREAD

**Issue by MengiFFW** [Social-Fire-HQ/website#2]
The Einsatzbericht contains HTML parts that should only be shown after certain radio button options or checkboxes are cheked. Should i implement a JavaScript for this or will this be managed by our backend?

**Comment by Ampferl** [comment]
For such features in forms, you should use JS. Except the user is able to read out unauthorized data. In this case, it would be outsourced to the backend.

It would be the best, to add a css class for the invisible area and assign it in Css to `display: none`. With JS you can then check whether a certain checkbox is checked and if this were the case you manipulate the DOM (Document Object Model) with JavaScript.

Example:
https://www.geeksforgeeks.org/how-to-show-and-hide-div-elements-using-checkboxes/

**Comment by Ampferl** [comment]
A quick side note: Put the JS in its own file like this `/assets/js/example.js` and not into the .html

**Comment by MengiFFW** [comment]
had a little bit problems in understanding the example provided by you (don't understand how it references to the classes). But i found another js solution. Works fine. Added it to the addTermin.html (see js in addTermin.js). Will change Einsatzbericht tomorrow.
